### ISSUE TITLE
OpenSSL Issues when Installing via Cocoapods

### ISSUE THREAD

**Issue by kmikael** [idnow/de.idnow.ios#22]
See https://github.com/idnow/de.idnow.ios/issues/1#issuecomment-222085101

**Comment by kmikael** [comment]
I quick-hack-fixed this issue with our app by removing OpenSSL and adding the headers, this way I can use OpenSSL in our app and the implementation of OpenSSL is in the IDnow static library.

But this is not a good long-term and stable solution.

An ideal solution would be for IDnow to use https://github.com/krzyzanowskim/OpenSSL for example as a dependency, then when the app also needs OpenSSL, Cocoapods can do its thing and everything will work out!

**Comment by hkretzschmar** [comment]
Hi kmikael,

I agree that removing OpenSLL on your side and depending on the implementation being present in a closed source binary is not a good solution. Since we will remove OpenTok from our dependencies with the next major release (3.0) the duplicate symbols problem will be gone, BUT for you this means that you have to undo the hack and add openssl again to your own code.

Kind regards
Holger Kretzschmar
