### ISSUE TITLE
Update dependencies

### ISSUE THREAD

**Issue by 0bmxa** [idnow/de.idnow.ios#23]
Please update the dependencies of IDNow, as newer versions of the dependencies are available. We'd especially like to upgrade AFNetworking and OpenTok to a more recent version.

Maybe also the reqiured OpenTok version to support bitcode can be updated, as they [keep on releasing betas](https://github.com/CocoaPods/Specs/tree/master/Specs/OpenTok) in parallel. (I'm, however, not sure, if these support bitcode.)

**Comment by hkretzschmar** [comment]
Hi Obmxa,

you can safely update AFNetworking yourself to the most current version, as the SDK supports AFNetworking up to version 3.1.0. 

`pod update AFNetworking`

As to OpenTok, at the moment we support OpenTok up to version 2.9.0 . Since updating requires not only to change the client side (SDK implementation) but also the IDnow backend, for the moment we will stay with this version. With the next major release (3.0) we will remove OpenTok/TokBox from our dependencies, which will eliminate the problem and in case you still need OpenTok you can use whatever version you need or want.

Kind regards
Holger Kretzschmar
