### ISSUE TITLE
Relax Sentry version constraint

### ISSUE THREAD

**Issue by sonicdoe** [idnow/de.idnow.ios#56]
[v3.20.0 currently depends on Sentry v4.0.1](https://github.com/CocoaPods/Specs/blob/4218b4ded06afa1d73200a9abf86c9e43ac6064a/Specs/b/2/e/IDnowSDK/3.20.0/IDnowSDK.podspec.json#L61-L63) (`~> 4.0.1` only matches v4.0.1). This makes it difficult to install the SDK if you are already using Sentry since v4.0.1 is already a year old and the latest version is v4.3.4.

It would be great if the version constraint could be relaxed to `~> 4.0`.

**Comment by phu-idnow** [comment]
Updated in v3.21.0

**Comment by sonicdoe** [comment]
Thank you for updating the version constraint, however, [`~> 4.3.4`](https://github.com/CocoaPods/Specs/blob/857992a4a21fc981d900185771bcffcdbab8a9d3/Specs/b/2/e/IDnowSDK/3.21.0/IDnowSDK.podspec.json#L61-L63) is also quite restrictive. For example, it won’t match [Sentry v4.4.0](https://github.com/getsentry/sentry-cocoa/releases/tag/4.4.0) which was released five days ago.

Would it be possible to relax the version constraint to `~> 4.3`, for example?

**Comment by phu-idnow** [comment]
Thanks for your suggestion.
we intent 4.3.x only now and will relax version constraint later

**Comment by boennemann** [comment]
Another two weeks passed without a comment even. Please get on this.

Thank you.

**Comment by phu-idnow** [comment]
hi,
Can you please create ticket via support.idnow.de

Thanks,

**Comment by boennemann** [comment]
Congratulations on the 4.0.0 release.

Unfortunately the release still depends on Sentry 4.3.4.

There is absolutely no reason whatsoever to have a hard dependency on Sentry for an SDK that's supposed to be consumed by another party. If you want to offer this then there is exactly one reasonable way: Add documentation for the feature in the first place (past "Added possibility to use Sentry logging") and make it optional. At this point nobody could even use this, but it's adding to everyone's bundle size **for no reason whatsoever** and blocking their own Sentry integration on ancient versions.

Version 4.3.4 of Sentry is **216** days old.

This ticket itself is **167** days old, with Sentry 4.4.0, the first incompatible version, being **159** days old.

All you need to do is: a) remove sentry, or b) if you really insist on having Sentry as a hard dependency (??? 🤯) then have some mercy with the engineers (who are usually forced to work with this piece of software) and keep this up to date on a regular and **timely** schedule.

> Can you please create ticket via support.idnow.de
You have this issue tracker open and this is an issue with your SDK. If you need this ticket in your own system somehow, then please go ahead and do that yourself.
This matter is embarrassing enough already.

Please excuse, if my absolute frustration and lack of patience is leaking through these lines, but we are not even talking about an actual implementation issue here. This comes down to a lack of discipline, understanding of SDK design principles, and empathy for your downstream consumers.

I'm asking you to please make this right now.
This is affecting not only other people's products, but also the reputation of IDnow engineering as a whole.

@arminbauer @souheib93 @phu-idnow @hkretzschmar @mredlin @kbarzen-idn @sonicdoe @BilelSelmiIDnow @GuillermoCiqueHolvi @iSapozhnik @sleski @SlawomirLeski @monisnap-julien @MathiasGrasy @vmalinskyi @p-fischer @philipp-idnow

**Comment by iSapozhnik** [comment]
@boennemann Not really sure why did you tag me but I'm fully with you!

**Comment by boennemann** [comment]
> @boennemann Not really sure why did you tag me but I'm fully with you!

I'm somewhat desperate trying to find the right person to take care of this. I assumed people contributing to the idnow repos are employees – that assumption was wrong. Sorry about that. I should have checked your profile.

**Comment by iSapozhnik** [comment]
@boennemann all good. The only reason why I did that contribution was the fact that I could not understand the documentation because there were too many typos and misspelled words. 🤷🏼‍♂️

**Comment by phu-idnow** [comment]
well, thank you all for your interest in this. We are planning to relax Sentry version 4.x (up to 5.0 but not include 5.0). And trying to make it optional.

Thanks

**Comment by phu-idnow** [comment]
> @boennemann all good. The only reason why I did that contribution was the fact that I could not understand the documentation because there were too many typos and misspelled words. 🤷🏼‍♂️

hi @boennemann , thank for your comment, could you please specify where make you misunderstand? It would be good if get some suggestions from yours.

Thanks,

**Comment by tjanela** [comment]
@boennemann, I could not agree with you more. 
It is unreasonable and a hinder to the developers that use this SDK, not updating a hard dependency regularly, or, alternatively, providing a mechanism to not depend on it at all.
It can also be a possible GDPR compliance issue. Speaking of GDPR it also represents a burden on our clients' DPOs since they now have one more partner to disclose and possible breaches to handle.
Adding to all of this, Sentry is an application monitoring tool and IDnow is a digital identification facilitator that handles extremely sensitive and private information. This is something that seems to have been taken lightly. My only hope is that this is only an impression. Having an outdated version like you have, as I'm sure you understand, does not shine a good light on this.

@phu-idnow regarding the state of your documentation, and general writing principles, it would be a good starting to point to enable syntax checking on your document editing tool and, at least, using something like Grammarly to help whoever is writing these docs in the English language.
Writing technical documents is, in itself, hard to do, let alone do well. To make matters worse it seems like English is not the writer's native language. I'd suggest using all the help you can get. Writing documents that are not understood is, frankly speaking, a waste of money, time, and credibility. It also misses the point of having documentation in the first place.

As a closing note, let me add that we use this SDK to develop state of the art applications, not to be hindered by it while doing so. Your team's decisions have an impact on our products, for the best and for the worst.

**Comment by boennemann** [comment]
> well, thank you all for your interest in this. We are planning to relax Sentry version 4.x (up to 5.0 but not include 5.0). And trying to make it optional.
> 
> Thanks

Have these plans manifested into something more concrete by now? Something we can plan with?

**Comment by NazarYablonskiy** [comment]
@phu-idnow please 🙏

**Comment by NazarYablonskiy** [comment]
Hi @phu-idnow, if you are aware of ETA for the new version with relaxed Sentry dep, could you please let us know? Thank you in advance!

**Comment by sonicdoe** [comment]
[v4.1.0](https://github.com/CocoaPods/Specs/blob/8ee9030452169a84f57a80e1f0e9ed52f1cc4451/Specs/b/2/e/IDnowSDK/4.1.0/IDnowSDK.podspec.json) no longer depends on Sentry so I’ll close this issue.

**Comment by boennemann** [comment]
A heads up for everyone subscribed to this ticket. 

v4.1.0 is even more broken than the versions before, because it doesn't remove Sentry, it only removes the dependency definition.
If you're using Sentry along with IDnow it will crash as soon as you try to capture an exception (ironic, I know).

Details here: #81
