### ISSUE TITLE
Check Objective-C style

### ISSUE THREAD

**Issue by kmikael** [idnow/de.idnow.ios#6]
Use, for example https://github.com/NYTimes/objective-c-style-guide

**Comment by hkretzschmar** [comment]
Hi kmikael,

since the only relevant part of this project contains the interface of the SDK we don't feel the need to adhere to one specific code style. The example is just what it is an example. Feel free to use whatever code style in your own project using our SDK. 

Kind regards
Holger Kretzschmar
