### ISSUE TITLE
Use an NSError instead of a custom class

### ISSUE THREAD

**Issue by kmikael** [idnow/de.idnow.ios#7]
`NSError` has all the properties you need and more and can be much more easily be integrated into existing workflows and code.

**Comment by macmacen** [comment]
Using NSError instead of IDnowError.
Additional Public Header has to be imported: NSError+IDnowError.h
IDnowError.h does no longer exist.

error.localizedDescription will still display a localised message of the error object (if needed).

Check for usage of IDnowError and replace it with NSError (concerning completion blocks and delegate callbacks).
